# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "postcss"
        versions: ["8.x"]
      - dependency-name: "sass-loader"
        versions: [ "11.x", "12.x", "13.x" ]
      - dependency-name: "eslint"
        versions: [ "7.x", "8.x" ]
      - dependency-name: "eslint-plugin-promise"
        versions: [ "5.x", "6.x" ]
      - dependency-name: "vue"
        versions: [ "3.x" ]
      - dependency-name: "@vue/cli-*"
        versions: [ "5.x" ]
      - dependency-name: "typescript"
        versions: [ "4.7" ]
    open-pull-requests-limit: 25
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "node"
        versions: [ "17-alpine", "18-alpine" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

